In [4]:
import numpy as np

# Zahlen bei der Ausgabe mit einer Nachkommastelle anzeigen
np.set_printoptions(formatter={'float_kind': lambda x: f"{x:.1f}"})

# Erste Zeile mit numpy.array()
row1 = np.array([-16.0, -12.0, -8.0, -4.0, 0.0, 4.0, 8.0, 12.0, 16.0])

# Zweite Zeile mit numpy.linspace()
row2 = np.linspace(-1.2, 1.2, 9)

# Dritte Zeile mit numpy.arange()
row3 = np.arange(8.0, -8.1, -2.0)

# Matrix A zusammensetzen
A = np.array([row1, row2, row3])

# Matrix B extrahieren (2. und 3. Zeile, 2., 5. und 8. Spalte)
B = A[1:3, [1, 4, 7]]

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)


Matrix A:
 [[-16.0 -12.0 -8.0 -4.0 0.0 4.0 8.0 12.0 16.0]
 [-1.2 -0.9 -0.6 -0.3 0.0 0.3 0.6 0.9 1.2]
 [8.0 6.0 4.0 2.0 0.0 -2.0 -4.0 -6.0 -8.0]]

Matrix B:
 [[-0.9 0.0 0.9]
 [6.0 0.0 -6.0]]
